services:
  - type: web
    name: phishing-scanner
    env: python
    buildCommand: ""
    startCommand: gunicorn server:app
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/huggingface
    plan: free
